CC = g++
CFLAGS = I
DEPS1 = IntegerArray.hpp  #//(this is fake fx)   // Dependency 

%.o: %.c $(DEPS1)
	$(CC) -c -o $@ $< $(CFLAGS)

buildall: main.o IntegerArray.o
	$(CC) -o main main.o IntegerArray.o
clean:
	bin/rm -rf *.o a.out